import * as esbuild from 'esbuild';

// Optional template engines pulled in by @vue/compiler-sfc (consolidate); we only use Vue templates.
const externalOptional = [
  'velocityjs',
  'dustjs-linkedin',
  'dustjs-helpers',
  'dust',
  'atpl',
  'liquor',
  'twig',
  'ejs',
  'eco',
  'jazz',
  'jqtpl',
  'hamljs',
  'hamlet',
  'whiskers',
  'haml-coffee',
  'hogan.js',
  'templayed',
  'handlebars',
  'underscore',
  'lodash',
  'pug',
  'then-pug',
  'jade',
  'then-jade',
  'qejs',
  'walrus',
  'mustache',
  'just',
  'ect',
  'mote',
  'toffee',
  'dot',
  'bracket-template',
  'ractive',
  'nunjucks',
  'htmling',
  'babel-core',
  'plates',
  'react-dom',
  'react',
  'vash',
  'slm',
  'marko',
  'teacup',
  'coffee-script',
  'squirrelly',
  'twing',
  'tinyliquid',
  'liquid-node',
  'swig',
  'swig-templates',
  'razor-tmpl',
  'arc-templates',
];

await esbuild.build({
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  outfile: 'dist/index.cjs',
  target: 'node20',
  banner: { js: '#!/usr/bin/env node' },
  external: externalOptional,
});
